#!/bin/sh

# Increment, decrement, or mute the volume and send a notification
# of the current volume level.
# https://github.com/ericmurphyxyz/dotfiles/blob/master/.local/bin/changevolume

send_notification() {
	pb_channels=$(amixer sget Master | awk '/Playback channels:/ {print $3}')
	volume=""

	if [ $pb_channels == "Mono" ]; then
    	volume=$(amixer get Master | awk '$0~/%/ {print $4}' | tr -d '[]%')
	else
    	volume=$(amixer get Master | awk -F'[][]' '/Left:/ { gsub(/%/, ""); print $2 }')
	fi

	dunstify -a "changevolume" -u low -r 9993 -h int:value:"$volume" -i "volume-$1" "Volume: ${volume}%" -t 2000
}

case $1 in
up)
	amixer sset Master 5%+ unmute
	send_notification "$1"
	;;
down)
	amixer sset Master 5%- unmute
	send_notification "$1"
	;;
mute)
	# amixer -q set Master toggle
	channel_count=$(amixer get Master | tail -2 | grep -c '\[on\]')
	if [ $((channel_count)) -ne 0 ]; then
		amixer sset Master mute
		dunstify -a "changevolume" -t 2000 -r 9993 -u low -i "volume-mute" "Muted"
	else
		amixer sset Master unmute
		send_notification up
	fi
	;;
esac
